# ~/.config/chezmoi/chezmoi.toml

ignorePatterns = [
  "*.secret", "*.key", "*.pem", "*.token", # 敏感文件
  "*.swp", "*.un~", "*~",                  # 编辑器临时文件
  ".DS_Store", "Thumbs.db",                # 系统垃圾文件
  ".git", ".gitignore",                    # 防止嵌套 git 目录
  "node_modules", "venv", ".venv"          # 编程环境依赖（误加会导致源目录爆炸
]

[edit]
command = "code"
args = ["--wait"]

[diff]
command = "delta"
# delta 默认就会处理颜色，不需要额外 args，除非你有特殊需求

[git]
autoCommit = true
autoPush = false

[cd]
command = "zsh" # 这样执行 chezmoi cd 时直接进入你熟悉的 zsh 环境

[apply]
refreshPeriod = "1m"
